### ISSUE TITLE
Will Zarr have parallel IO through MPI?

### ISSUE THREAD

**Issue by liangwang0734** [zarr-developers/zarr#375]
Is it in the yearly plan at all? This feature perhaps will need a native C/C++/Fortran binding for:

- slicing
- chunking

Thread-safety is often not a big issue here since in MPI-paradigm each processor handles a different block of the data in the single output file. But of course, thread-safety is highly desired and can be vital in hybrid MPI/OpenMP programming.

**Comment by jakirkham** [comment]
Thus far users of Zarr have happily used it with at least a few parallel programming paradigms I'm aware of. A few that I know of include Dask, Spark, and ipyparallel. Though am not aware of any limitations that would block it from use in other parallel paradigms. In fact, given ipyparallel has an [MPI backend]( https://ipyparallel.readthedocs.io/en/latest/mpi.html ), that might be a reasonable way to initially play with MPI support.

As to language support, there are a few different implementations of the spec for different languages. Since you mention C++, you may want to take a look at [z5]( https://github.com/constantinpape/z5 ). There are not yet C or Fortran implementations. However (as you have already noticed) there has been some recent discussion about a C implementation in issue ( https://github.com/zarr-developers/zarr/issues/317 ). Your input would be welcome there. Expect Fortran is of interest as well. Feel free to raise a separate issue on that point.

There is [synchronization support]( https://zarr.readthedocs.io/en/stable/api/sync.html ) that users can bolt onto a store if needed. Some [stores]( https://zarr.readthedocs.io/en/stable/api/storage.html ) have their own form of synchronization (e.g. some databases). There has been some work recently to expand the available selection on this front.

Hope this information helps and provides you some ideas as to what is already possible. Feel free to ask any other questions that come to mind.

**Comment by rabernat** [comment]
I have found it extremely easy to use zarr from mpi4py. Here is an example script:
https://github.com/rabernat/zarr_hdf_benchmarks/blob/master/parallel_read_write.py

As long as your mpi ranks are not trying to write to the same chunks, you don't have to worry about sync at all!

**Comment by jakirkham** [comment]
Any other thoughts here, @liangwang0734, or is this good to close?

**Comment by jakirkham** [comment]
If more issues come up, would be happy to discuss.

**Comment by hongyx11** [comment]
May I ask are there any news about parallel IO through MPI? It will be very useful when deploying on a supercomputer since the nodes number is large.

**Comment by jakirkham** [comment]
@hongyx11, not understanding the question. As noted above this should already be workable. Would suggest trying one of the approaches above and reporting any issues encountered

**Comment by rabernat** [comment]
Perhaps we should try to address this explicitly in the docs, since it is clearly of interest to users.

**Comment by jakirkham** [comment]
Maybe there could be a notebook that does this with [`concurrent.futures`]( https://docs.python.org/3/library/concurrent.futures.html ) and works more-or-less the same with different parallel frameworks

**Comment by MSanKeys963** [comment]
> Maybe there could be a notebook that does this with [`concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html) and works more-or-less the same with different parallel frameworks

Something for the Outreachy intern to look into? 
CC: @joshmoore  @jakirkham @rabernat

**Comment by joshmoore** [comment]
Certainly no objections, @MSanKeys963.
